<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net9.0;net48</TargetFrameworks>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <xRetrySpecFlowVersion Condition="'$(xRetrySpecFlowVersion)' == ''">1.9.0</xRetrySpecFlowVersion>
    <RestorePackagesPath>$(BaseIntermediateOutputPath)packages</RestorePackagesPath>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="xretry.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
    <PackageReference Include="xRetry.SpecFlow" Version="$(xRetrySpecFlowVersion)" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="4.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>

    <!-- required for .net framework xunit tests to run on mono via dotnet test: https://github.com/microsoft/vstest/issues/2469 -->
    <PackageReference Include="Microsoft.TestPlatform.ObjectModel" Version="18.9.0" />
  </ItemGroup>

</Project>
