<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net9.0;net48</TargetFrameworks>
    <OutputType>Exe</OutputType>
    <LangVersion>13.0</LangVersion>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <xRetryV3ReqnrollVersion Condition="'$(xRetryV3ReqnrollVersion)' == ''">0.1.0-alpha1</xRetryV3ReqnrollVersion>
    <RestorePackagesPath>$(BaseIntermediateOutputPath)packages</RestorePackagesPath>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="xretry.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.0" />
    <PackageReference Include="Reqnroll.xunit.v3" Version="3.3.2" />
    <PackageReference Include="xRetry.v3.Reqnroll" Version="$(xRetryV3ReqnrollVersion)" />
    <PackageReference Include="xunit.v3" Version="3.2.2" />
    <PackageReference Include="xunit.v3.core" Version="3.2.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>

    <!-- required for .net framework xunit tests to run on mono via dotnet test: https://github.com/microsoft/vstest/issues/2469 -->
    <PackageReference Include="Microsoft.TestPlatform.ObjectModel" Version="18.0.0" />
  </ItemGroup>

</Project>
