name: CI/CD

on:
  push:
  pull_request:

jobs:
  ci_build:
    name: CI Build
    runs-on: ubuntu-latest
    container: joshkeegan/dotnet-mixed-build:7.0
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Lint
        working-directory: build
        run: make lint

      - name: Build
        working-directory: build
        run: make build
      
      - name: Run Unit Tests
        working-directory: build
        run: make unit-tests-run

      - name: Create Nuget Packages
        working-directory: build
        run: make nuget-create
      
      - name: Upload artefacts
        uses: actions/upload-artifact@v3
        with:
          name: artefacts
          path: artefacts
        if: ${{ always() }}
      
      - name: Upload deployment scripts
        uses: actions/upload-artifact@v3
        with:
          name: deploy
          path: deploy
  
  ci_docs:
    name: CI Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate docs
        working-directory: docs
        run: make all

      - name: Check no modified files (docs must be generated locally & checked in)
        run: |
          git update-index --refresh
          git diff-index --quiet HEAD --
  
  cd:
    name: CD
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/sdk:6.0.102-bullseye-slim
    needs: 
      - ci_build
      - ci_docs
    if: github.ref == 'refs/heads/release'
    steps:
      - name: Download deployment scripts
        uses: actions/download-artifact@v4
        with:
          name: deploy
          path: deploy
      
      - name: Download artefacts
        uses: actions/download-artifact@v4
        with:
          name: artefacts
          path: artefacts

      - name: Release
        working-directory: deploy
        run: /bin/bash deploy.sh ${{ secrets.NUGET_API_KEY }}