name: Docs

on:
  push:
  pull_request:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate docs
        working-directory: docs
        run: make all

      - name: Check no modified files (docs must be generated locally & checked in)
        run: |
          git update-index --refresh
          git diff-index --quiet HEAD --